### ISSUE TITLE
能否改成文字形式提示

### ISSUE THREAD

**Issue by QAQBing** [D-Bood/reCAPTCHAv3#1]
在站点评论区加入代码后，右下角会有一个图标，会挡住站点的返回顶部图标，之前看wp有个插件是直接在评论框下面内显示This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.
还想请问下可以实现嘛...

**Comment by D-Bood** [comment]
据我的了解，右下角的图标是根据Google那边接受请求后传回的数据自动加载的
希望你给我那个wp插件的地址，我来参考一下
这插件只是我业余做的，最近实在没啥时间，可以的话希望你能发个PR

P.S.
Google一下
在你的blog的style.css里头加上这个
.grecaptcha-badge {
display: none !important;
}
那个东西应该就不会出现了
等有时间了我准备在插件设置里头集成一下

**Comment by QAQBing** [comment]
你好，WP的插件地址是https://wordpress.org/plugins/google-captcha/  另外想问下我在登录页面加了代码但评论区没有加代码，评论功能无法正常发送，是哪里有问题么...还是说评论和登录界面必须同时加入代码呢...

**Comment by D-Bood** [comment]
@Dogou
这个插件影响不到后台吧……只是跟评论有关系
你是不是用了别的插件？

**Comment by QAQBing** [comment]
我用的是第三方主题，这个<?php reCAPTCHAv3_Plugin::output(); ?>应该放在哪里最合适呢😳

**Comment by D-Bood** [comment]
@Dogou 
就找到你的主题的style.css或者类似的文件
然后copy&paste就行了
Ctrl+F5强制刷新一下，应该就生效了
我在我自己的博客里面测试正常
